### PR TITLE
Persisted dark and light mode through all pages

### PR DESCRIPTION
**Pull request by sallyhoneybee**
# Description

Created light mode and toggle switch in header bar.
Persisted dark and light mode through all pages.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Toggle

Screenshot 2023-03-29 at 1 24 24 AM
Screenshot 2023-03-29 at 1 24 43 AM

- [x] Lightmode

Screenshot 2023-03-29 at 1 25 35 AM

- [x] Persistence
Screenshot 2023-03-29 at 1 26 09 AM
Screenshot 2023-03-29 at 1 26 32 AM

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have added proof(eg. screenshots) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by weepotty** [comment]
Wow great job! I can't see the scss file changes though

**Comment by sallyhoneybee** [comment]
> Wow great job! I can't see the scss file changes though 

OH YES CAUSE AHAHA I forgot that I had to merge my branch that yall already approved and then pushed my changes on the branch. I realised my PR wasnt merged yet and merged it. So my initial changes are in my previous pr HAAH

**Comment by weepotty** [comment]
Ah no wonder Hahah ok approved

**Review by weepotty — APPROVED** [review]
Beaut

**Pull request merged**
